version: "3.8"

services:
  frontend:
    build: .
    volumes:
      - .:/app:cached
      - frontend:/app/build
      - ~/.bash_history:/root/.bash_history
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
    command: sh -c "yarn && yarn start"

volumes:
  frontend:
